### ISSUE TITLE
"Log in to interact" Button Issue

### ISSUE THREAD

**Issue by Shivansh070707** [tokamak-network/tokamak-bridge#121]
The "Log in to interact" button is visible in the bridge and swap section of the application, but it is not clear what action is required or why this button is necessary. The button is located at the bottom of the page, but it seems disconnected from the rest of the UI elements. On clicking in the button it ask for vercel login.

Severity: High

Steps to Reproduce

Navigate to the Bridge & Swap section.
Observe the "Log in to interact" button at the bottom of the page.

Actual Behavior
The button is present but does not provide clear guidance on its purpose.
It seems unrelated to the main interaction elements on the page.
<img width="1278" alt="Screenshot 2024-09-02 103901" src="https://github.com/user-attachments/assets/04b0960c-c908-44bc-96ae-1c98d5ffff40">
<img width="1280" alt="Screenshot 2024-09-02 103553" src="https://github.com/user-attachments/assets/dd221a67-ecec-4ab9-9b32-3b1062a9edfa">

**Comment by suahnkim** [comment]
@Shivansh070707 thank you for reporting, but this is a testing page specific feature that connects to vercel for error reporting. 

I will ask @SonYoungsung to disable this feature for next test
