### ISSUE TITLE
Thanos Sepolia Network Selection Not Working

### ISSUE THREAD

**Issue by Shivansh070707** [tokamak-network/tokamak-bridge#122]
Severity: Medium

Description:
When selecting "Thanos Sepolia" as the network in the Bridge & Swap section, the interface displays "Select Network" instead of allowing further interaction. However, the "Sepolia" and "Titan Sepolia" networks are functioning as expected.

Steps to Reproduce:
Navigate to the Bridge & Swap section.
Select "Thanos Sepolia" as the network.
Observe that the interface shows "Select Network" and does not allow further interaction.

Expected Behavior:
The "Thanos Sepolia" network should function similarly to "Sepolia" and "Titan Sepolia," allowing the user to proceed with the swap or bridge transaction. Alternatively, if "Thanos Sepolia" is not intended to be supported, it should be removed from the list of available network options.

Actual Behavior:
The "Thanos Sepolia" network displays "Select Network" and halts further interaction, preventing users from proceeding with their transactions.

<img width="1278" alt="image" src="https://github.com/user-attachments/assets/d291e7ea-8010-4dda-9956-2a20937ee3e3">

**Comment by suahnkim** [comment]
Thanos Sepolia is not supported. Please check the [testing scope](https://medium.com/tokamak-network/tokamak-bridge-cross-trade-public-test-dee7fd3d2b0e#:~:text=Network%3A%20Sepolia%20and%20Titan%20Sepolia%20(Mainnet%20and%20Thanos%20Sepolia%20is%20not%20supported))
