### ISSUE TITLE
provide-receive countdown

### ISSUE THREAD

**Issue by monica-tokamak** [tokamak-network/tokamak-bridge#125]
receive countdown not working
Stuck at 00:00 and showing as complete to provide

![스크린샷 2024-09-02 오후 3 07 21](https://github.com/user-attachments/assets/27d0d04a-44b2-4573-b7ea-26f1154b9ca3)
![스크린샷 2024-09-02 오후 3 07 25](https://github.com/user-attachments/assets/9b652f60-8469-450d-8bf0-49af25f83c55)
![스크린샷 2024-09-02 오후 3 09 48](https://github.com/user-attachments/assets/814c58bf-0d98-4f03-82d9-ecfff1c557af)

**Comment by SonYoungsung** [comment]
it's working well on my side. could you check again?
![image](https://github.com/user-attachments/assets/735077f3-e83c-417f-b370-783d7caddbed)
![image](https://github.com/user-attachments/assets/24b4ef8f-cae8-42c6-9170-62b6486a5f9f)
