### ISSUE TITLE
[Cross Trade - Frontend & Backend bugs]:Footer Improvement

### ISSUE THREAD

**Issue by Shivansh070707** [tokamak-network/tokamak-bridge#126]
Severity : Tips or suggestion
Description :
In the footer section, the "Tokamak Network" link is not redirecting to the Tokamak Network website .Consider adding link to tokamak official page when clicking on "Tokamak Network"

<img width="1280" alt="image" src="https://github.com/user-attachments/assets/7b2a7907-d2d4-40b9-8dd9-4264ad4f7a4b">

**Comment by monica-tokamak** [comment]
Thank you for your suggestion.

**Comment by monica-tokamak** [comment]
@SonYoungsung
