### ISSUE TITLE
The amount is not exact.

### ISSUE THREAD

**Issue by zzooppii** [tokamak-network/tokamak-bridge#133]
TON amount visible on screen
![DDDD6349-C14C-40C2-94A0-714025DBE101](https://github.com/user-attachments/assets/e750b4e0-723b-44c8-96c7-3df181949a0e)

The amount actually have
![1E03467C-9869-4B06-AC9D-C21FDF8B86E6](https://github.com/user-attachments/assets/b34963d7-bbcd-47b8-a592-04b3c3ae7a15)

**Comment by SonYoungsung** [comment]
can you check you have really 1,001 TON in your account? because theis might be possible to show the balance with round-up.

**Comment by zzooppii** [comment]
I checked and it seems that the titanSepolia explorer value is rounded.
Thank you for your reply.
