### ISSUE TITLE
[Cross Trade - Frontend & Backend bugs]:"Next" Button Remains Disabled After Transaction Request Despite Sufficient Balance

### ISSUE THREAD

**Issue by Shivansh070707** [tokamak-network/tokamak-bridge#135]
Severity: Medium

Description:

After completing a transaction request, the "Next" button remains disabled even though the user has sufficient balance. To proceed, users must refresh the page and re-select the token to request again.

This issues occurs when my transaction is confirmed but UI didn't show any "Transaction confirmed" .

Expected Behavior:

After completing a transaction, the "Next" button should be enabled automatically if there is sufficient balance for the next action, allowing users to proceed without refreshing the page.

Actual Behavior:

The "Next" button remains disabled after a transaction request, requiring users to refresh the page and re-select the token to proceed.

<img width="1268" alt="image" src="https://github.com/user-attachments/assets/8cc087ac-2722-40a2-8df8-dc465055f957">

**Comment by SonYoungsung** [comment]
First of all, thansk for your reporting. 

I failed to reproduce this bug. I'd really appreciate if you try it again when you have a chance. and let me know it it's still happened.

**Comment by Shivansh070707** [comment]
This issue happened when I submitted the tx and Tx was confirmed but not
reflected in the FE

**Comment by SonYoungsung** [comment]
Thx! I think I know why it's happened now.
