### ISSUE TITLE
[Cross Trade - Frontend & Backend bugs]: Column Titles Clarity

### ISSUE THREAD

**Issue by rishabh-sharma0x00** [tokamak-network/tokamak-bridge#144]
### Can you specify where the bug exists?

Cross Trade Provide UI

### What happened?

To avoid confusion, I suggest reversing the column names in the table to accurately reflect the values being exchanged. For example I did a tx of 9.9465 TON from Titan to Sepolia for 10 TON. But actually the reverse happened. Attaching the screenshots below

### What browsers are you seeing the problem on?

Chrome

### Upload any screenshots to aid with explaining the bug.

TON Balance Before

![Screenshot from 2024-09-02 16-06-37](https://github.com/user-attachments/assets/8940f55b-f43c-47c3-a28b-828bc075ac50)
![Screenshot from 2024-09-02 16-06-19](https://github.com/user-attachments/assets/bf46574e-0710-4ca5-8193-f6ffcc96487d)

TON Cross_Bridge Available Options

![Screenshot from 2024-09-02 16-07-34](https://github.com/user-attachments/assets/dc3a68bf-b1af-4c87-9bf3-cea1f6e869af)

TON Balance After

![Screenshot from 2024-09-02 16-15-15](https://github.com/user-attachments/assets/069e6719-ea2e-44f2-8381-2bddde3a7da7)
![Screenshot from 2024-09-02 16-14-42](https://github.com/user-attachments/assets/456e1079-2cab-420f-9da5-18cdeaa8ffbc)

**Comment by SonYoungsung** [comment]
I think it's the similar issue with #146. Network symbol will be fixed and then it could help you not get confused with balance. 

Thanks for your reporting!
