### ISSUE TITLE
[Cross Trade - Suggestion]: I would like to suggest that Profit be decimalized.

### ISSUE THREAD

**Issue by mandoopapa** [tokamak-network/tokamak-bridge#147]
### What is your recommendation for?

Others

### Explain your suggestion

I'd like to see 0.xxx as a decimal point, but I'd like to see 2-3 decimal places to accurately show the profit since it's not like there is no profit at all.

<img width="499" alt="image" src="https://github.com/user-attachments/assets/a5729cdf-6695-4d78-91a6-ab4e0cb56fb3">

**Comment by monica-tokamak** [comment]
Thank you for your suggestion.
We will reflect on it soon.

**Comment by monica-tokamak** [comment]
@SonYoungsung 
There should be a decimal point guide for profit.
I'll let you know when it's ready.

**Comment by SonYoungsung** [comment]
Your suggestion has been impleneted with #159. 
Thanks for your suggestion! :)
