### ISSUE TITLE
[Cross Trade - Suggestion]: UI 관련 제안 (Provide 상세 내역, Profit 정렬, 네트워크 언더바 삭제)

### ISSUE THREAD

**Issue by mandoopapa** [tokamak-network/tokamak-bridge#159]
### What is your recommendation for?

Cross Trade Provide UI, Others

### Explain your suggestion

UI와 관련된 사소한 제안을 몇가지 정리해 공유드립니다.

1. Cross Trade를 통한 Provide의 상세 내역을 볼 수 있는 방법의 변경이 있었으면 좋겠습니다.

![image](https://github.com/user-attachments/assets/f00c0610-14ef-4b6c-a5e3-6ec14d887e5e)
![image](https://github.com/user-attachments/assets/55edd741-2411-45e8-8a51-cc5ce17e5a9d)

현재는 위 그림의 1번과 같이 날짜를 클릭하면 아래와 같은 상세내역을 볼 수 있는 창이 뜨는데, 2번과 같이 상세내역을 확인할 수 있는 영역을 크게 만들거나(빨간선), Provide 내에 토글 형태로 볼 수 있도록 하면 어떨까 싶습니다.

![image](https://github.com/user-attachments/assets/09fb2a01-a4c0-4e23-8336-942794cb8d83)

Provide, Approve하게 되면 위와 같은 이미지가 표시되는데, 이 이미지가 직관적으로 보여서 형태를 변경하는 것도 좋은 방법이 될 것 같다는 의견입니다.

2. Cross Trade의 Network 현황 표시에 언더바가 들어갑니다. 언더바가 없어도 될 것 같습니다.

![image](https://github.com/user-attachments/assets/47278a0d-ed86-414b-ba3f-d78ade2b4fe9)

**Comment by mandoopapa** [comment]
![image](https://github.com/user-attachments/assets/9d94c5d6-8c8a-455b-bacc-6f8ecce48aef)

추가로 Receive나 Provide는 순서정렬이 가능한 것으로 보이는데, Profit은 순서정렬이 안되는 것 같습니다. 사용자들이 가장 관심갖는 것은 Profit이 아닐까 싶습니다. Profit에 대한 순서정렬이 필요해보입니다.

**Comment by monica-tokamak** [comment]
Thank you for your various opinions.
-Considered usability by using common components on mobile and desktop.
-It will be updated regarding the toast message.
-This is before deployment.

**Comment by monica-tokamak** [comment]
@SonYoungsung 
-Please sort the profit area, too
