### ISSUE TITLE
[Cross Trade - Frontend & Backend bugs]: approve btn and toast message

### ISSUE THREAD

**Issue by monica-tokamak** [tokamak-network/tokamak-bridge#163]
### What happened?

approve can't be visible at the same time as the enabled button and the toast message

### Upload any screenshots to aid with explaining the bug.

Upload image here
![스크린샷 2024-09-04 오후 3 58 11](https://github.com/user-attachments/assets/8a93c762-2777-40ca-94cf-1ffdc80a9130)

**Comment by SonYoungsung** [comment]
We should put some delay toast messages comes up to fix this issue because it's coming from network factors.
