### ISSUE TITLE
[Cross Trade - Frontend & Backend bugs]: cancel-toast message link

### ISSUE THREAD

**Issue by monica-tokamak** [tokamak-network/tokamak-bridge#174]
### What happened?

When selecting a (cancel)toast message, it is connected to the provide tab

### Upload any screenshots to aid with explaining the bug.

Upload image here
![스크린샷 2024-09-05 오후 3 14 38](https://github.com/user-attachments/assets/697c2e6a-8033-4ff9-ace4-c5625848d875)
![스크린샷 2024-09-05 오후 3 14 58](https://github.com/user-attachments/assets/bf1d8257-a29e-4954-9c44-082178c69483)

**Comment by SonYoungsung** [comment]
I think it might be happened when you closed the history tab with Provide section and open it with the Toast. Please check it again when label is changed to "done".

**Comment by monica-tokamak** [comment]
After refreshing, I canceled it again, When selecting the toast message, go to the provide.
For a moment, it looks like provide is a deposit.

![스크린샷 2024-09-06 오후 1 54 55](https://github.com/user-attachments/assets/fc4aa48a-9f85-401d-9eba-2a73a620fcbd)

https://github.com/user-attachments/assets/23d0328a-bb10-40ee-9ce2-a6671a1d230d
