### ISSUE TITLE
[Cross Trade - Frontend & Backend bugs]: Receive percentage value is wrong on Edit Request modal.

### ISSUE THREAD

**Issue by usgeeus** [tokamak-network/tokamak-bridge#181]
### Can you specify where the bug exists?

Cross Trade Settings (fees, etc)

### What happened?

Receive percentage value is wrong on Edit Request modal.
![image](https://github.com/user-attachments/assets/4f432a35-194e-4723-bcac-c782d5e12d1c)

### What browsers are you seeing the problem on?

Chrome

### Upload any screenshots to aid with explaining the bug.

Upload image here

**Comment by SonYoungsung** [comment]
this issue is resolved with #184
