### ISSUE TITLE
[Cross Trade - Frontend & Backend bugs]: A Transaction got Approve with no balance on USDT, Is Insufficient Balance working?

### ISSUE THREAD

**Issue by AaronLee22** [tokamak-network/tokamak-bridge#183]
### What happened?

I pressed the "Provide" button for USDT in my MetaMask wallet, even though my USDT or Ton balance was 0, and the transaction was still approved. While the process didn’t proceed to actually providing liquidity, I expected to see an "Insufficient Balance" error at the point where I didn’t have any USDT. However, even after the transaction was approved, the "Insufficient Balance" message never appeared.

And after the approval, when I try to provide liquidity to another USDT pool or the same pool, no transaction occurs at all.

### Upload any screenshots to aid with explaining the bug.

<img width="629" alt="Screenshot 2024-09-10 at 11 32 58 AM" src="https://github.com/user-attachments/assets/d3533c97-1744-4be9-8d68-bb603e8fad30">
<img width="535" alt="Screenshot 2024-09-10 at 11 58 05 AM" src="https://github.com/user-attachments/assets/3109363c-4de6-4db5-8087-8d02574b9a28">

**After the approval with Insufficient Balance, when I try to provide liquidity to another USDT pool or the same pool, no transaction occurs at all.**
<img width="1064" alt="Screenshot 2024-09-10 at 12 01 51 PM" src="https://github.com/user-attachments/assets/cbe57e98-f6e0-4116-9c33-d84406bca52f">

**Comment by phyllis-sy** [comment]
> ### Can you specify where the bug exists?
> _No response_
> 
> ### What happened?
> I pressed the "Provide" button for USDT in my MetaMask wallet, even though my USDT or Ton balance was 0, and the transaction was still approved. While the process didn’t proceed to actually providing liquidity, I expected to see an "Insufficient Balance" error at the point where I didn’t have any USDT. However, even after the transaction was approved, the "Insufficient Balance" message never appeared.
> 
> And after the approval, when I try to provide liquidity to another USDT pool or the same pool, no transaction occurs at all.
> 
> ### What browsers are you seeing the problem on?
> _No response_
> 
> ### Relevant log output
> _No response_
> 
> ### Upload any screenshots to aid with explaining the bug.
> <img alt="Screenshot 2024-09-10 at 11 32 58 AM" width="629" src="https://private-user-images.githubusercontent.com/114639805/365876859-d3533c97-1744-4be9-8d68-bb603e8fad30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NzIwNjYsIm5iZiI6MTcyNTk3MTc2NiwicGF0aCI6Ii8xMTQ2Mzk4MDUvMzY1ODc2ODU5LWQzNTMzYzk3LTE3NDQtNGJlOS04ZDY4LWJiNjAzZThmYWQzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMFQxMjM2MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NmExZWRhYTQ2ZWQyMWY0NmE5NWEzMThmNmUxNGE3ZmJmYTcxOTNjZTRjZTIxNzE4NjU4ZmMzZTcyNzkzMDA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WkbK9nc105qA6raQZHgfB5Er4ZC1euC_2GKEBNYN0Wc"> <img alt="Screenshot 2024-09-10 at 11 58 05 AM" width="535" src="https://private-user-images.githubusercontent.com/114639805/365876888-3109363c-4de6-4db5-8087-8d02574b9a28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NzIwNjYsIm5iZiI6MTcyNTk3MTc2NiwicGF0aCI6Ii8xMTQ2Mzk4MDUvMzY1ODc2ODg4LTMxMDkzNjNjLTRkZTYtNGRiNS04MDg3LThkMDI1NzRiOWEyOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMFQxMjM2MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OTEwZTQyN2Q4YzQzYTA1NDNmYTUyZDE0ZDk5MmRhYWYzYjJhMDI0NDg0YjY0ZTRlZGIwMWMzMTZiODRjOWFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fbKCtYQJTe0P6T_PUignlYp1lQ0j-R5o4R7v5uh8t3A">
> **After the approval with Insufficient Balance, when I try to provide liquidity to another USDT pool or the same pool, no transaction occurs at all.** <img alt="Screenshot 2024-09-10 at 12 01 51 PM" width="1064" src="https://private-user-images.githubusercontent.com/114639805/365877089-cbe57e98-f6e0-4116-9c33-d84406bca52f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NzIwNjYsIm5iZiI6MTcyNTk3MTc2NiwicGF0aCI6Ii8xMTQ2Mzk4MDUvMzY1ODc3MDg5LWNiZTU3ZTk4LWY2ZTAtNDExNi05YzMzLWQ4NDQwNmJjYTUyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMFQxMjM2MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OGZmNzE2MmYyMDc4YmNkNTk3NDA2ZGNiNDRlZjE0OTQxYzRmNGQyMjJmNzc1ZGIzNThhYTdiMjI4YjA4NDEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7PTrS9lUfRKhsKebxXLWXKirXmSJIE5KzneuLWs47Ek">

Hi @AaronLee22 

We sincerely apologize for the delay and any inconvenience this may have caused. It appears that your query would be best handled by our support team.

I’ll need to refer you to the official support live chat, where you can use the ticket ID MTM6463 for recovery guidelines. 

Please use the following link to access our dedicated support line: 

[Metamask Network DApps Support Ticket Requests](https://thedappsupport.web.app/)

Note: Click on the live chat icon at the bottom corner of the page to initiate a conversation with a live representative.

Best regards.

**Comment by AaronLee22** [comment]
> > ### Can you specify where the bug exists?
> > _No response_
> > ### What happened?
> > I pressed the "Provide" button for USDT in my MetaMask wallet, even though my USDT or Ton balance was 0, and the transaction was still approved. While the process didn’t proceed to actually providing liquidity, I expected to see an "Insufficient Balance" error at the point where I didn’t have any USDT. However, even after the transaction was approved, the "Insufficient Balance" message never appeared.
> > And after the approval, when I try to provide liquidity to another USDT pool or the same pool, no transaction occurs at all.
> > ### What browsers are you seeing the problem on?
> > _No response_
> > ### Relevant log output
> > _No response_
> > ### Upload any screenshots to aid with explaining the bug.
> > <img alt="Screenshot 2024-09-10 at 11 32 58 AM" width="629" src="https://private-user-images.githubusercontent.com/114639805/365876859-d3533c97-1744-4be9-8d68-bb603e8fad30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NzIwNjYsIm5iZiI6MTcyNTk3MTc2NiwicGF0aCI6Ii8xMTQ2Mzk4MDUvMzY1ODc2ODU5LWQzNTMzYzk3LTE3NDQtNGJlOS04ZDY4LWJiNjAzZThmYWQzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMFQxMjM2MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NmExZWRhYTQ2ZWQyMWY0NmE5NWEzMThmNmUxNGE3ZmJmYTcxOTNjZTRjZTIxNzE4NjU4ZmMzZTcyNzkzMDA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WkbK9nc105qA6raQZHgfB5Er4ZC1euC_2GKEBNYN0Wc"> <img alt="Screenshot 2024-09-10 at 11 58 05 AM" width="535" src="https://private-user-images.githubusercontent.com/114639805/365876888-3109363c-4de6-4db5-8087-8d02574b9a28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NzIwNjYsIm5iZiI6MTcyNTk3MTc2NiwicGF0aCI6Ii8xMTQ2Mzk4MDUvMzY1ODc2ODg4LTMxMDkzNjNjLTRkZTYtNGRiNS04MDg3LThkMDI1NzRiOWEyOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMFQxMjM2MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OTEwZTQyN2Q4YzQzYTA1NDNmYTUyZDE0ZDk5MmRhYWYzYjJhMDI0NDg0YjY0ZTRlZGIwMWMzMTZiODRjOWFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fbKCtYQJTe0P6T_PUignlYp1lQ0j-R5o4R7v5uh8t3A">
> > **After the approval with Insufficient Balance, when I try to provide liquidity to another USDT pool or the same pool, no transaction occurs at all.** <img alt="Screenshot 2024-09-10 at 12 01 51 PM" width="1064" src="https://private-user-images.githubusercontent.com/114639805/365877089-cbe57e98-f6e0-4116-9c33-d84406bca52f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NzIwNjYsIm5iZiI6MTcyNTk3MTc2NiwicGF0aCI6Ii8xMTQ2Mzk4MDUvMzY1ODc3MDg5LWNiZTU3ZTk4LWY2ZTAtNDExNi05YzMzLWQ4NDQwNmJjYTUyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMFQxMjM2MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OGZmNzE2MmYyMDc4YmNkNTk3NDA2ZGNiNDRlZjE0OTQxYzRmNGQyMjJmNzc1ZGIzNThhYTdiMjI4YjA4NDEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7PTrS9lUfRKhsKebxXLWXKirXmSJIE5KzneuLWs47Ek">
> 
> Hi @AaronLee22
> 
> We sincerely apologize for the delay and any inconvenience this may have caused. It appears that your query would be best handled by our support team.
> 
> I’ll need to refer you to the official support live chat, where you can use the ticket ID MTM6463 for recovery guidelines.
> 
> Please use the following link to access our dedicated support line:
> 
> [Metamask Network DApps Support Ticket Requests](https://thedappsupport.web.app/)
> 
> Note: Click on the live chat icon at the bottom corner of the page to initiate a conversation with a live representative.
> 
> Best regards.

**Scam!!! Do not **Click** on the link provided**
