### ISSUE TITLE
[Cross Trade - Contract Bugs]: There is a vulnerability in the provideCT method that allows front-running

### ISSUE THREAD

**Issue by blackcow1987** [tokamak-network/tokamak-bridge#188]
### What happened?

A malicious user can force the victim to pay more tokens than expected by frontrunning the editFee method when the victim calls the provideCT method.

=> https://github.com/tokamak-network/tokamak-bridge/blob/public-test/crosstrade/contracts/L1/L1CrossTrade.sol#L100

**Comment by zzooppii** [comment]
Thank you @blackcow1987 
I will change it so that I also receive the edit amount when providingCT.

**Comment by zzooppii** [comment]
@blackcow1987 
https://github.com/tokamak-network/crossTrade/commit/c28bb0ac5078d921e021ded84132a5205f487e49

I have revised what you said.

If you have any additional comments, please let me know.

**Comment by blackcow1987** [comment]
I will review the changes !
