### ISSUE TITLE
[Cross Trade - Suggestion]:  Network Naming 

### ISSUE THREAD

**Issue by NegruGeorge** [tokamak-network/tokamak-bridge#191]
### What is your recommendation for?

Network Naming 

### Explain your suggestion

**Naming problem** 

Instead of `Titan_sepolia` we should have  `Titan Sepolia` 
![Screenshot from 2024-09-11 22-40-54](https://github.com/user-attachments/assets/e0b8560f-b996-4778-a5b0-b5a60ea997ed)

**Comment by monica-tokamak** [comment]
Thank you for the suggestion. I think we missed it
