### ISSUE TITLE
[Cross Trade - Frontend & Backend bugs]: Provide Tokens for YOURSELF 

### ISSUE THREAD

**Issue by NegruGeorge** [tokamak-network/tokamak-bridge#192]
### Can you specify where the bug exists?
https://dev-tokamak-bridge.vercel.app/pools
In pools / pools modal

### What happened?

I could Provide tokens on Sepolia with the same address that initiated the request on Titan Sepolia. 
1. go to provide.
2. disconnect the wallet
3. click provide on your own request
4. connect wallet in the request modal
5. You can provide for yourself now

Demo video on how it worked: 

[Screencast from 2024-09-11 23-10-28.webm](https://github.com/user-attachments/assets/0d9a509e-42fc-46c9-95c1-0c0987c04d06)

Notes: The Smart contract allow one user to provide for himself. 

transaction that was made on sepolia:
https://sepolia.etherscan.io//tx/0x6a833b49d4a27605e79c726ee77ddb382229ec6815fc038b532aa13f0704cce6

transaction on titan sepolia: https://explorer.titan-sepolia.tokamak.network/tx/0x800a3f841d415e8fc0d49526fccea6a5b506ad2a6dcd343a88ec4df33092ff25

### What browsers are you seeing the problem on?

Google Chrome 

### Upload any screenshots to aid with explaining the bug.

video above

**Comment by SonYoungsung** [comment]
@monica-tokamak should we add a new design for this case or just pop up the edit modal or close?

**Comment by SonYoungsung** [comment]
We've decided to close the modal when this case comes up anywhere. Any other things will be automatically changed based on account change on SPA, so don't need to refresh it. 

Thanks for your help!
