### ISSUE TITLE
[Cross Trade - Suggestion]: Add emergency claim feature to L2 contract

### ISSUE THREAD

**Issue by blackcow1987** [tokamak-network/tokamak-bridge#199]
### What is your recommendation for?

Others

### Explain your suggestion

If a user enters an incorrect chainId, there needs to be a way to retrieve the token. If not, you should look into managing the whitelist by chainId.

**Comment by monica-tokamak** [comment]
@zzooppii

**Comment by zzooppii** [comment]
In L2, settings are made for Chain. Are you suggesting that it would be good to have a whitelist for Chain in L1?

**Comment by blackcow1987** [comment]
@zzooppii Yes, I think it is necessary as entering the wrong chain ID can cause your assets to be frozen.

**Comment by zzooppii** [comment]
If you enter an incorrect chainID, the transaction will not go through because it will be different from the hash value. (Except in the case where you intentionally enter an incorrect chainID and enter an incorrect hash value)

**Comment by blackcow1987** [comment]
@zzooppii Yes, but I felt it could be problematic as incorrect input could potentially result in assets being frozen.

**Comment by zzooppii** [comment]
Yes, that's right.

If you enter incorrect information, your funds may be frozen.

We will discuss this again.

**Comment by zzooppii** [comment]
@blackcow1987 
https://github.com/tokamak-network/crossTrade/commit/5f2c636a419040df4c090dc491e5f6017a4c37fb
When requesting requestNonRegisteredToken, if you enter the wrong chainId, your funds may be frozen, so i added a require statement to check whether you entered the chainId we support.

Thank you
