### ISSUE TITLE
[Cross Trade - Suggestion]: Remove saleCount & chainId from calldata

### ISSUE THREAD

**Issue by blackcow1987** [tokamak-network/tokamak-bridge#200]
### What is your recommendation for?

Others

### Explain your suggestion

Since the two values ​​are already applied to the hash value, there is no need to pass them additionally via calldata.

https://github.com/tokamak-network/tokamak-bridge/blob/public-test/crosstrade/contracts/L2/L2CrossTrade.sol#L399
```
        hashValue = getHash(
            _l1token,
            _l2token,
            msg.sender,
            _totalAmount,
            _ctAmount,
            _saleCount,
            startChainId,
            _endChainId
        );
```

**Comment by blackcow1987** [comment]
When building calldata in the L1CrossTrade contract, change it so that data that is already applied to the hash is not added.
```
    function makeEncodeWithSignature(
        uint8 number,
        address to, 
        uint256 amount,
        bytes32 byteValue
    )
        private
        view
        returns (bytes memory)
    {
        uint256 chainId = _getChainID();
        if (number == CLAIM_CT) {
            return abi.encodeWithSignature("claimCT(address,uint256,bytes32)", 
                to, 
                amount,
                byteValue
            );
        } else {
            return abi.encodeWithSignature("cancelCT(address,bytes32)", 
                to,
                byteValue
            );
        }
```

Replace the key of dealData, where transaction information is stored in the L2 contract, with the hash value from saleCount.
```
...
mapping(bytes32 => RequestData) public dealData;
...
```

The L2 contract reads dealData with the hash value passed through the L1 contract and checks the chainId / saleCount values.
```
function claimCT(
    ...
    RequestData memory data = dealData[_hash];
    ...
```

**Comment by monica-tokamak** [comment]
@zzooppii

**Comment by zzooppii** [comment]
When creating a hash value, create it with keccak256.
Keccak256 is a type of SHA-3 and is a one-way encryption.

Can you infer the saleCount value through the hash value?

**Comment by blackcow1987** [comment]
@zzooppii chainId and saleCount data is stored in dealData. So you don't need to pass it to L2 as a parameter. Only the hash value calculated in L1 needs to be passed to L2.

**Comment by zzooppii** [comment]
Now I understand.
First, the mapping structure of dealData is changed and applied.
I am accepting the change positively.

However, the current Titan version will be opened soon.
So, it will not be applied to the Titan version, and we will discuss whether to apply it to the Thanos version that will be created later.

Thank you for your good feedback.

**Comment by zzooppii** [comment]
@blackcow1987 
It is difficult to apply in the current version, and I will test how much GasFee is reduced in the future and apply it.

Thank you.
