### ISSUE TITLE
[Cross Trade - Suggestion]: Use the latest version of the solidity compiler

### ISSUE THREAD

**Issue by blackcow1987** [tokamak-network/tokamak-bridge#201]
### Explain your suggestion

The current codebase is using solc 0.8.24. The latest version is 0.8.27, so it is recommended to use the latest version.

https://github.com/tokamak-network/tokamak-bridge/blob/public-test/crosstrade/contracts/L2/L2CrossTrade.sol#L2
```
// SPDX-License-Identifier: Unlicense
pragma solidity 0.8.24;
```

**Comment by monica-tokamak** [comment]
@zzooppii

**Comment by zzooppii** [comment]
Thanks for the great feedback.

What would be better for our code if we changed from 0.8.24 to the current 0.8.27?

**Comment by blackcow1987** [comment]
@zzooppii You can use require statement with custom error, and If you don't have a special reason, I think it's always a good idea to use the latest version of the compiler.

**Comment by zzooppii** [comment]
@blackcow1987 
I will apply it to the Thanos version.

Thank you.
