### ISSUE TITLE
[Cross Trade - Suggestion]: Use custom error

### ISSUE THREAD

**Issue by blackcow1987** [tokamak-network/tokamak-bridge#202]
### Explain your suggestion

Since solc 0.8.26, a patch has been made to allow custom errors in require statements. It is recommended to change this as it is much more gas-efficient than using strings in require statements.

https://docs.soliditylang.org/en/v0.8.27/contracts.html#custom-errors

**Comment by monica-tokamak** [comment]
@zzooppii

**Comment by zzooppii** [comment]
Thanks for the feedback. I'll talk about that when we discuss the issues.

**Comment by zzooppii** [comment]
@blackcow1987 
I will apply it to the Thanos version.

Thank you.

**Comment by zzooppii** [comment]
Duplicate of #201
