### ISSUE TITLE
[Cross Trade - Suggestion]: Use storage for registered token pairs for gas saving

### ISSUE THREAD

**Issue by blackcow1987** [tokamak-network/tokamak-bridge#204]
### Explain your suggestion

When registerToken is performed in the L2 contract, you can reduce the size of the calldata added to the rollup by issuing an ID for the l1/l2 token pair and changing the contract to use that ID.

```
    function registerToken(
        address _l1token,
        address _l2token,
        uint256 _l1chainId
    )
        external
        onlyOwner
    {
        bytes32 id = keccak256(abi.encode(_l1chainId, _l1token, _l2token));
        require(registeredPair[id].l1Token == address(0), "already registerToken");
        registeredPair[id] = RequestedPair({
            l1token: _l1token,
            l2token: _l2token,
            chainId: _endChainId,
        });
    }

    ...

    function requestRegisteredToken(
        bytes32 _id,
        uint256 _totalAmount,
        uint256 _ctAmount,
    )
        external
        payable
        onlyEOA
        nonZero(_totalAmount)
        nonZero(_ctAmount)
        nonReentrant
    {
        require(registeredToken[id].l1token != address(0), "not register token");
```

**Comment by monica-tokamak** [comment]
@zzooppii

**Comment by zzooppii** [comment]
This is a good way to reduce the size of calldata to the function.

However, I know that the gas cost is higher for loading values ​​from storage than for using input values.

So I think we need to discuss whether to apply this part.

Thank you for your good opinion.

**Comment by blackcow1987** [comment]
storage cost is expensive then input data, but in L2 these data is stoted in L1 through rollup. So I think it is important to minimize overall calldata.

**Comment by zzooppii** [comment]
We will discuss the relevant part.

Thank you for the good feedback!

**Comment by zzooppii** [comment]
@blackcow1987 
We will not change it right now, but we will consider supporting that part in the future.

Thank you.
