### ISSUE TITLE
[Cross Trade - Frontend & Backend bugs]: Can't trade a new token

### ISSUE THREAD

**Issue by NegruGeorge** [tokamak-network/tokamak-bridge#205]
### What happened?

Describe the bug and its behavior! You can also upload the image and code links (public-test/crosstrade branch)

I deployed a new token on Titan Sepolia => TonFake token.  https://explorer.titan-sepolia.tokamak.network/token/0x0515Cbc459a2795b3D74933ebf34cC0F0f74856B/token-transfers

I can't  trade the token because is not a registered one. I assume requestNonRegisteredToken function is not yet available on the frontend. 
I could approve the token and also click the request. It might be a good idea to disable the next button for non registered tokens ( so users can't go to the part where they approve the tokens and also press the request button and get an error message )  
[Screencast from 2024-09-15 13-46-24.webm](https://github.com/user-attachments/assets/6121d1ca-0539-4998-9fb6-003b5413083c)

### Upload any screenshots to aid with explaining the bug.

video above

**Comment by SonYoungsung** [comment]
will be fixed with this issue #210
