### ISSUE TITLE
[Cross Trade - Contract Bugs]: Remove onlyEOA modifier for forward compatibility

### ISSUE THREAD

**Issue by blackcow1987** [tokamak-network/tokamak-bridge#209]
### What happened?

After EIP-3074, arbitrary code can be executed in EOA as well, and these restrictions are not effective for preventing reentrancy, etc. Since there is no code vulnerable to re-entrancy, it is recommended to remove unnecessary restrictions for compatibility reasons.

**Comment by zzooppii** [comment]
Thank you for your advice. We will discuss this matter and handle it accordingly.

**Comment by zzooppii** [comment]
@blackcow1987 
This part is not going to change for now.
We will apply it in the Thanos version or solve it in another way.

Thank you.
